<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Authors>hu-ja-ja</Authors>
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="WindowController.Core.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Serilog" Version="4.3.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>

</Project>
